/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "on-tertiary-fixed": "#380d00",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#0040a2",
        "surface-container-highest": "#e1e2ec",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "surface-tint": "#0c56d0",
        "inverse-surface": "#2e3038",
        "tertiary-fixed-dim": "#ffb59b",
        "surface-variant": "#e1e2ec",
        surface: "#faf8ff",
        "secondary-fixed": "#dae2fd",
        primary: "#003d9b",
        "tertiary-container": "#a33500",
        "surface-container": "#ededf8",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#b2c5ff",
        "surface-container-low": "#f3f3fd",
        "on-tertiary-fixed-variant": "#812800",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#0052cc",
        "on-background": "#191b23",
        "secondary-container": "#dae2fd",
        "on-surface": "#191b23",
        "on-surface-variant": "#434654",
        secondary: "#565e74",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        outline: "#737685",
        background: "#faf8ff",
        "on-primary-fixed": "#001848",
        "primary-fixed": "#dae2ff",
        "surface-bright": "#faf8ff",
        "on-primary-container": "#c4d2ff",
        "on-tertiary-container": "#ffc6b2",
        "error-container": "#ffdad6",
        "outline-variant": "#c3c6d6",
        "tertiary-fixed": "#ffdbcf",
        "surface-dim": "#d9d9e4",
        "surface-container-high": "#e7e7f2",
        tertiary: "#7b2600",
        "primary-fixed-dim": "#b2c5ff",
        "inverse-on-surface": "#f0f0fb",
        "on-secondary-fixed": "#131b2e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "0.25rem",
        "2xl": "3rem",
        base: "4px",
        gutter: "24px",
        sm: "0.5rem",
        md: "1rem",
        xl: "2rem",
        lg: "1.5rem",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-md": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      animation: {
        marquee: "marquee 30s linear infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
    },
  },
  plugins: [],
};
